### ISSUE TITLE
Required state does not behave correctly

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-custom-field#31] opened 2019-05-23 08:45 UTC
When the `required` attribute is set on `vaadin-custom-field`, the field behaves weird (at least in respect of `vaadin-text-field`):

1. the blue dot does not hide when the field is filled, but it turns red;
2. if left empty, the dot stays blue instead of turning red;
3. when filled, the field shifts down.

![2019-05-23 10-38-41 2019-05-23 10_39_34](https://user-images.githubusercontent.com/851745/58238229-2b0e0580-7d47-11e9-92af-296e4b6b6074.gif)

Glitch: https://glitch.com/edit/#!/brick-magic

I would expect the field to be invalid if at least one of the wrapped field is invalid.

**Comment by web-padawan** [comment] 2019-06-11 12:49
Confirmed. There are at least two issues here:

1. incorrect styles for required indicator (blue dot)

2. incorrect approach used to tweak alignment
https://github.com/vaadin/vaadin-custom-field/blob/710180827fbefd77cfcbca00c46f17b8add6b15a/theme/lumo/vaadin-custom-field-styles.html#L35-L37

The above should not apply when there is no error message.

**Comment by Haprog** [comment] 2019-06-17 10:15
> 1. the blue dot does not hide when the field is filled, but it turns red;

It seems to add `invalid` attribute when a value is set and does not set `has-value` attribute.

> 2. if left empty, the dot stays blue instead of turning red;

Clearing the value from a `required` field should set `invalid` attribute but instead it seems to remove the `invalid` attribute.

> 3. when filled, the field shifts down.

Incorrect CSS for `::before` element as pointed out above.

Overall it seems that the logic for `invalid` (in relation to `required`) is inverse from what it should be and `has-value` doesn't seem to be implemented at all (but that is required by the [`lumo-required-field`](https://github.com/vaadin/vaadin-lumo-styles/blob/master/mixins/required-field.html#L49) styles for hiding the required indicator).

**Comment by Haprog** [comment] 2019-06-17 11:20
`invalid` behaviour is inverted because here https://github.com/vaadin/vaadin-custom-field/blob/master/src/vaadin-custom-field-mixin.html#L130 `validate()` is being called (with the old value) before setting the new value (which is coming from a `change` event in wrapped component).

This seems to have been always broken in custom field (since this validation was added).

This part is at least an easy fix, but will require some new tests to make sure it doesn't break again.

**Comment by Haprog** [comment] 2019-06-18 10:09
The validation logic and required indicator styling (`has-value`) has been fixed in `master` (#38).

Only issue remaining (for this issue) is the vertical alignment with/without `error-message`. @platosha is working on it.

**Comment by web-padawan** [comment] 2019-06-19 11:35
> Only issue remaining (for this issue) is the vertical alignment 

Fixed by #40 so I'm closing this issue.

**Closed by web-padawan** 2019-06-19 11:35 UTC
Labels: BFP, bug
