### ISSUE TITLE
Width of CustomFields in FormLayout

### ISSUE THREAD

**Issue by tulioag** [vaadin/vaadin-custom-field#28] opened 2019-04-05 13:07 UTC
https://github.com/vaadin/vaadin-custom-field-flow/issues/18

**Expected behavior**
Width of `CustomField` should be 100% like other fields in `FormLayout`.
![excpected](https://user-images.githubusercontent.com/45820614/55625353-c869a600-57a8-11e9-9d93-c3205d5212d5.png)
**Actual behavior**
A `Div` in `shadow-root` of `<vaadin-custom-fields>` prevents the `FormLayout` inside the `CustomField` from expanding correctly.
![actual](https://user-images.githubusercontent.com/45820614/55625485-3dd57680-57a9-11e9-81d1-2439f1ac9b45.png)
![div](https://user-images.githubusercontent.com/45820614/55625491-4332c100-57a9-11e9-9c2c-d3e6ae5993a4.gif)

The behavior described in the issue above is not related to flow and can be reproduced with the following code.

 ```html
   <vaadin-form-layout >
      <vaadin-text-field label="Name"></vaadin-text-field>
      <vaadin-custom-field style="width:100%;height: 100%">
          <vaadin-form-layout style="width:100%;height: 100%">
              <vaadin-text-field label="City"></vaadin-text-field>
              <vaadin-text-field label="Address" ></vaadin-text-field>
          </vaadin-custom-field>
      </vaadin-custom-field>
    </vaadin-form-layout>
```

**Comment by web-padawan** [comment] 2019-04-09 08:03
I don't think that 2 nested `vaadin-form-layout` components are supported use case. At least, they currently do not work that way in IE11. See also vaadin/vaadin-form-layout#106

Unlike text-field, select or other components, custom field doesn't expand to full width also because of the fact that it is generally supposed to wrap several components together.

And we have never considered using `vaadin-form-layout` inside `vaadin-custom-field`, so that's not a supported use case either. Can you elaborate more on what alignment would you expect?

**Comment by JohannesLaidler** [comment] 2019-04-09 10:10
The issue is not related to nested `vaadin-form-layouts`'s. The nested `vaadin-form-layout` can be replaced by any Layout: e.g. `vaadin-vertical-layout`.

Even when all components inside `CustomField` and `CustomField` itself ar set to `width: 100%`, the `CustomField` does not expand like other fields added to the `FormLayout`.

![field-width](https://user-images.githubusercontent.com/45820614/55789837-661be880-5abb-11e9-8426-d83e628e656a.gif)

### Nested FormLayouts
> And we have never considered using vaadin-form-layout inside vaadin-custom-field, so that's not a supported use case either. Can you elaborate more on what alignment would you expect?


An example for the nested `vaadin-form-layout` would be if there is a `CustomField` consisting of multiple fields which should align fields in 2 columns if there is enough space for that or change to 1 column if not.

For example: 
We have multiple input forms which need a address. So we create a `CustomField` (in Java) which already pre-configures all field witdh/caption/data/validation/alignment/etc . This allows us to manage the field at a central location and have no code duplication (Which works fine if no `CustomField` is used).
`CustomField` has red border:

### Alignment on smaller screens

![custom-field](https://user-images.githubusercontent.com/45820614/55791138-24d90800-5abe-11e9-9c4d-d0ecd4e72d82.gif)

### width of `CustomField` not working like other fields in `FormLayout`
![custom-field-width](https://user-images.githubusercontent.com/45820614/55791964-f3f9d280-5abf-11e9-8b1b-b4c97071ac30.gif)

**Comment by nrapel** [comment] 2019-05-31 15:05
I have the same problem and it's not because of the fact that the CustomField contains a FormLayout (in my case I have only one TextField with prefix a Select field
![custom-field-problem-1](https://user-images.githubusercontent.com/32927980/58715002-a1a5a580-83ce-11e9-848e-8661af54fc47.png)
) but rather the fact that the <div> container cannot get width 100% when the CustomField is inside a Form Layout. 

so the problem is that although the CustomField by itself does occupy 100% of the space the container div doesn't, thus a) the textfield is smaller than the full size (making it stand out of the other textfields etc that are 100% and b) a lot of unused space is left unusable.

**Comment by urkl** [comment] 2019-12-04 15:13
Is there some progress on this bug?

**Comment by urkl** [comment] 2019-12-04 20:21
Did somebody override this bug somehow?

**Comment by syampillai** [comment] 2019-12-13 04:54
CustomFields are used by me in many places in FormLayout and in most of the places, I need the embedded components within the CustomField should be expanded to 100%. However, it is not needed in some cases. So, I feel that, while fixing this issue, a method to set the content width would be great - something like expandContentFull() or setContentWidth(...).

**Comment by web-padawan** [comment] 2019-12-13 08:52
@syampillai you are correct. Outside `vaadin-form-layout` we don't want custom field to expand.
Otherwise the inputs inside it would not stay on the same line (but instead wrap to the next one).

This can not be fixed by CSS only from the inside of `vaadin-custom-field`.
Ideally this would be use case for a `:host-context` selector. But it's not widely supported.

The possible workaround would be to detect the parent dynamically in JS.

But the point is: method or property to toggle width of the custom field is needed. 
So this issue needs a new API. That's why I marked it as an enhancement.

**Comment by vaadin-miki** [comment] 2019-12-20 07:54
@web-padawan there already is a method to toggle width of the custom field, it is called `setWidthFull()` - I would expect it to do exactly what it says, including the delegation of `width: 100%` to the container

do you think it would be a reasonable solution?

**Comment by Haprog** [comment] 2019-12-20 08:02
I feel like the container should have width 100% by default and then you can control the width just by setting width on the custom field element itself (or using `setWidthFull()`).

Does someone have any use case where this would not make sense or where you would need some other width on the container?

**Comment by vaadin-miki** [comment] 2019-12-20 08:06
I cannot think of any reason why the container `div` should behave different from `vaadin-custom-field` - also the `div` is not present in the server-side api and there is no way to control it, so it makes perfect sense for it to be 100% wide by default (or mirror whatever settings are done to `vaadin-custom-field`

**Comment by Haprog** [comment] 2019-12-20 08:13
I think this should be fixed simply by adding `width: 100%` here https://github.com/vaadin/vaadin-custom-field/blob/master/src/vaadin-custom-field.html#L31-L34

But it needs to be tested that it doesn't break any obvious use cases. I'd like to consider this as a bug, unless I'm misunderstanding something.

**Comment by urkl** [comment] 2019-12-20 08:13
> I think this should be fixed simply by adding `width: 100%` here https://github.com/vaadin/vaadin-custom-field/blob/master/src/vaadin-custom-field.html#L31-L34
> 
> But it needs to be tested that it doesn't break any obvious use cases. I'd like to consider this as a bug, unless I'm misunderstanding something.

I tested this and it's working as expected for me.

**Comment by Haprog** [comment] 2019-12-20 08:19
We should probably add similar visual tests here as I have added in vaadin-date-time-picker for testing how the width behaves when setting `width` on the custom field:
- https://github.com/vaadin/vaadin-date-time-picker/blob/master/test/visual/test.js#L25-L37
- https://github.com/vaadin/vaadin-date-time-picker/blob/master/test/visual/flex-behaviour.html#L15_L33

**Comment by TatuLund** [comment] 2019-12-30 07:31
Isn't this same as https://github.com/vaadin/vaadin-custom-field/issues/45 actually ?

**Comment by web-padawan** [comment] 2019-12-30 08:18
Based on the discussion, including https://github.com/vaadin/vaadin-custom-field/issues/28#issuecomment-567834494 I conclude this should be fixed.

Also, the original code is there since cb14caa60b53480a47be39c910a74240c72ead45 (initial implementation). 

And the absence of `width: 100%` can be most likely explained by the fact that `div` do has full width by default (but not with `display: flex`, in that case it must be set explicitly).

My previous concern from https://github.com/vaadin/vaadin-custom-field/issues/28#issuecomment-565356302 turns out to be invalid, so I agree with the change. 
At least the behavior with `width: 100%` seems more predictable.

I will add the visual tests as suggested above.

**Closed** 2019-12-30 09:22 UTC
